---
- name: install npm and node
  become: yes
  apt:
    name: "{{ item.name }}"
    state: present
  with_items:
  - name: nodejs
  - name: npm

- name: set path for global npm packages
  become: no
  command: bash -lc "npm config set prefix /home/{{ this_user }}/.npm-global"
