---
- name: install general-purpose packages
  sudo: yes
  apt:
    name: "{{ item.name }}"
    state: present
  with_items:
  - name: gnome-tweaks
- name: install reflect, for autostart tests on change
  command: bash -lc "go get github.com/cespare/reflex"
